name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Build the pkg and test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest
        git clone https://github.com/tree-sitter/tree-sitter-python
        python -m ayni.build
    - name: Test
      run: pytest -vv
